### ISSUE TITLE
Draft and brainstorming for the 10th edition foreword

### ISSUE THREAD

**Issue by tmr83** [sultan-of-rum/morrowind-scripting-for-dummies#6]
The Tamriel Rebuilt project releases this 10th edition of the Morrowind Scripting Guide for Dummies to be developed collaboratively on Github at $LINK to provide updates and corrections to the 9th edition by porting to LaTeX. Please send bug reports to this repository.

I might also mention the Morrowind Code Patch and the current version of the CS. Any additional input would be appreciated.

**Comment by sultan-of-rum** [comment]
Good thinking!

Since the other prefaces have a very conversational tone, I think we can use this space for more informal things, too. We might mention the long history of use this document has had in the MW modding community, the recent renaissance of MW modding, how the TR team has in the past decade collected a large volume of errata, etc.

Also we might mention what's ahead -- MWSE-lua and OpenMW-lua. This version of the book will likely be rather bittersweet, as the intention of the modding community (though not TR, currently) seems to be to move beyond MWScript.

**Comment by tmr83** [comment]
Can you or someone write about those topics you mentioned? I would like to add the foreword soon, but I would only mention at this point that the purpose is to add the TR information and that the doc uses default OpenMW-CS syntax highlighting. And of course where to submit bug reports and other contributions.
